### ISSUE TITLE
segmentation fault with honeyd

### ISSUE THREAD

**Issue by ftrole** [sefcom/honeyplc#2]
I followed the instructions in the README to run honeyplc but when I execute the command:
` $ sudo honeyd -d -f config.s7-300 192.168.0.0/24 `

I receive as output:

```
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[12109]: started with -d -f config.s7-300 192.168.0.0/24
honeyd[12109]: listening promiscuously on enp0s3: (arp or ip proto 47 or (udp and src port 67 and dst port 68) or (ip and (net 192.168.0.0/24))) and not ether src 08:00:27:84:8a:1d
honeyd[12109]: Demoting process privileges to uid 65534, gid 65534
Segmentation fault (core dumped)
honeyd[12109]: Subsystem "/usr/share/honeyd/s7commServer" died
```

**Comment by MaoBoXing** [comment]
Have you installed Honeyd before

**Comment by ftrole** [comment]
Yes, I have installed and also used honeyd with other configurations, the problem appears to be in this specifical configuration of honeyplc (configuration file or the s7comm server) but I can't understand what's wrong

**Comment by MaoBoXing** [comment]
It looks like we have the same problem

**Comment by nonoti1** [comment]
Same problem here, did anyone come right with this one?

**Comment by ftrole** [comment]
Yes, the problem is caused by the s7comm server which needs to be executed with the ip address to listen on.
The solution I have come out with consists in starting the server on localhost:

`./server 127.0.0.1`

and then in the honeyd configuration file proxy your local 102 tcp port instead of using subsystem virtualization:

`add siemens tcp port 102 proxy 127.0.0.1:102 `

**Comment by securenetworx-shark** [comment]
Same issue :( the TCP port redirection not help.

**Comment by Key98pl** [comment]
I know this ticket hasn't been touched in a long time, but I too am having the same issue running honeyplc in honeyd.

I followed the steps as mentioned by ftrole:

1. Start the S7commserver:

```
user@plc:/usr/share/honeyd$ sudo ./s7commServer 127.0.0.1
2025-05-17 09:15:53 Server started`
```

2. Start honeyd using the s7-300 config file:

```
user@plc:~/Honeyd/myconfigs$ sudo honeyd -d -f config.s7-300 192.168.1.62
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[2855]: started with -d -f config.s7-300 192.168.1.62
honeyd[2855]: listening promiscuously on enp1s0: (arp or ip proto 47 or (udp and src port 67 and dst port 68) or (ip and (host 192.168.1.62))) and not ether src 52:54:00:74:3e:92
honeyd[2855]: Demoting process privileges to uid 65534, gid 65534
Segmentation fault (core dumped)
honeyd[2855]: Subsystem "/usr/share/honeyd/s7commServer" died
```

## My config file looks as follows:

```
user@plc:~/Honeyd/myconfigs$ cat config.s7-300 
create base
add base subsystem "/usr/share/honeyd/s7commServer" shared restart
add base tcp port 102 proxy 127.0.0.1:102

clone host1 base
set host1 personality "Siemens Simatic 300 programmable logic controller"


bind 192.168.1.62 host1
```
