### ISSUE TITLE
s7commServer install issues

### ISSUE THREAD

**Issue by offblacc** [sefcom/honeyplc#6]
Hi!

I am having problems while running Honeyd because of a missing Srv_SetSZL symbol; that led me to believe i hadn't really installed s7commServer and/or snap7 (correctly). 

Issue: 
```
root@plc:/honey# honeyd -d -f honeyd/myconfigs/config.s7-300 10.0.0.0/24
Honeyd V1.6d Copyright (c) 2002-2007 Niels Provos
honeyd[133]: started with -d -f honeyd/myconfigs/config.s7-300 10.0.0.0/24
honeyd[133]: listening promiscuously on eth0: (arp or ip proto 47 or (udp and src port 67 and dst port 68) or (ip and (net 10.0.0.0/24))) and not ether src 42:00:aa:00:00:03
honeyd[133]: Demoting process privileges to uid 65534, gid 65534
/usr/share/honeyd/s7commServer: symbol lookup error: /usr/share/honeyd/s7commServer: undefined symbol: Srv_SetSZL
honeyd[133]: Subsystem "/usr/share/honeyd/s7commServer" died
honeyd[133]: Restarting subsystem "/usr/share/honeyd/s7commServer"
/usr/share/honeyd/s7commServer: symbol lookup error: /usr/share/honeyd/s7commServer: undefined symbol: Srv_SetSZL
honeyd[133]: Subsystem "/usr/share/honeyd/s7commServer" died
```

All I did install-wise was (part of my docker setup script for the PLC node):

```bash
sudo apt update && sudo apt install software-properties-common -y
sudo add-apt-repository ppa:gijzelaar/snap7
sudo apt-get update
sudo apt-get install libsnap7-1 libsnap7-dev -y

echo "# ====== S300 fingerprint =======" >> /usr/share/honeyd/nmap-os-db
cat honeyplc-source/plc-profiles/Siemens\ S7-300/s7-300-nmap-fingerprint.txt >> /usr/share/honeyd/nmap-os-db

cp honeyplc-source/snap7/build/bin/x86_64-linux/libsnap7.so-300 /usr/lib/
cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
chmod 777 /usr/share/honeyd/s7commServer
```

The main issue and question is how to fix the issue of the unknown symbol, and how to do the setup step from your readme:

Install S7comm Server and library.

* Install the modified Snap7 [libsnap7.so](https://github.com/sefcom/honeyplc/tree/master/snap7/build/bin/x86_64-linux) file:

`/usr/lib/libsnap7.so`

* Install the [s7commServer](https://github.com/sefcom/honeyplc/blob/master/snap7/examples/cpp/x86_64-linux/server):

`/usr/share/honeyd/s7commServer`

`chmod 777 s7commServer`

Any help would be appreciated and thanks in advance!

**Comment by offblacc** [comment]
To install the libs:
```bash
honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
```

Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped

**Comment by ringringboy** [comment]
> To install the libs:
> 
> ```shell
> honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> ```
> 
> Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped



> To install the libs:
> 
> ```shell
> honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> ```
> 
> Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped

hi，how to install s7commserver,do as this?

cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
chmod 777 /usr/share/honeyd/s7commServer

**Comment by ringringboy** [comment]
> To install the libs:
> 
> ```shell
> honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> ```
> 
> Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped

hi，how to install s7commserver,do as this?

cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
chmod 777 /usr/share/honeyd/s7commServer

**Comment by offblacc** [comment]
This is from my install script, the part that does s7commserver installation. Just bear in mind - I never got everything to successfully work, I was getting https://github.com/sefcom/honeyplc/issues/2 . However, I could successfully start the server (to the best of my knowledge, I installed it successfully). I don't have that virtual machine anymore, but do have old notes and all of the code backed up so feel free to ask if you get stuck again.

```bash
# install S7comm Server and library.
cd honeyplc-source/snap7/build/unix
make -f x86_64_linux.mk install
cd ../../../..

echo "# ====== S300 fingerprint =======" >> /usr/share/honeyd/nmap-os-db
cat honeyplc-source/plc-profiles/Siemens\ S7-300/s7-300-nmap-fingerprint.txt >> /usr/share/honeyd/nmap-os-db

cp honeyplc-source/snap7/build/bin/x86_64-linux/libsnap7.so-300 /usr/lib/
cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
chmod 777 /usr/share/honeyd/s7commServer

```

**Comment by offblacc** [comment]
> > To install the libs:
> > ```shell
> > honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped
> 
> hi，how to install s7commserver,do as this?
> 
> cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer chmod 777 /usr/share/honeyd/s7commServer

This is from my install script, the part that does s7commserver installation. Just bear in mind - I never got everything to successfully work, I was getting https://github.com/sefcom/honeyplc/issues/2 . However, I could successfully start the server (to the best of my knowledge, I installed it successfully). I don't have the virtual machine that this was on anymore, but do have old notes and all of the code backed up so feel free to ask if you get stuck again.

```bash
# install S7comm Server and library.
cd honeyplc-source/snap7/build/unix
make -f x86_64_linux.mk install
cd ../../../..

echo "# ====== S300 fingerprint =======" >> /usr/share/honeyd/nmap-os-db
cat honeyplc-source/plc-profiles/Siemens\ S7-300/s7-300-nmap-fingerprint.txt >> /usr/share/honeyd/nmap-os-db

cp honeyplc-source/snap7/build/bin/x86_64-linux/libsnap7.so-300 /usr/lib/
cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
chmod 777 /usr/share/honeyd/s7commServer

```

**Comment by ringringboy** [comment]
> > > To install the libs:
> > > ```shell
> > > honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped
> > 
> > 
> > hi，how to install s7commserver,do as this?
> > cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer chmod 777 /usr/share/honeyd/s7commServer
> 
> This is from my install script, the part that does s7commserver installation. Just bear in mind - I never got everything to successfully work, I was getting #2 . However, I could successfully start the server (to the best of my knowledge, I installed it successfully). I don't have the virtual machine that this was on anymore, but do have old notes and all of the code backed up so feel free to ask if you get stuck again.
> 
> ```shell
> # install S7comm Server and library.
> cd honeyplc-source/snap7/build/unix
> make -f x86_64_linux.mk install
> cd ../../../..
> 
> echo "# ====== S300 fingerprint =======" >> /usr/share/honeyd/nmap-os-db
> cat honeyplc-source/plc-profiles/Siemens\ S7-300/s7-300-nmap-fingerprint.txt >> /usr/share/honeyd/nmap-os-db
> 
> cp honeyplc-source/snap7/build/bin/x86_64-linux/libsnap7.so-300 /usr/lib/
> cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
> chmod 777 /usr/share/honeyd/s7commServer
> ```

thank you so much！  In the path "**/usr/share/honeyd**", s7commServer not found, Do I need to create a s7commServer file?
after installing **Honeyd**, will there be this folder?

**Comment by offblacc** [comment]
> > > > To install the libs:
> > > > ```shell
> > > > honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped
> > > 
> > > 
> > > hi，how to install s7commserver,do as this?
> > > cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer chmod 777 /usr/share/honeyd/s7commServer
> > 
> > 
> > This is from my install script, the part that does s7commserver installation. Just bear in mind - I never got everything to successfully work, I was getting #2 . However, I could successfully start the server (to the best of my knowledge, I installed it successfully). I don't have the virtual machine that this was on anymore, but do have old notes and all of the code backed up so feel free to ask if you get stuck again.
> > ```shell
> > # install S7comm Server and library.
> > cd honeyplc-source/snap7/build/unix
> > make -f x86_64_linux.mk install
> > cd ../../../..
> > 
> > echo "# ====== S300 fingerprint =======" >> /usr/share/honeyd/nmap-os-db
> > cat honeyplc-source/plc-profiles/Siemens\ S7-300/s7-300-nmap-fingerprint.txt >> /usr/share/honeyd/nmap-os-db
> > 
> > cp honeyplc-source/snap7/build/bin/x86_64-linux/libsnap7.so-300 /usr/lib/
> > cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
> > chmod 777 /usr/share/honeyd/s7commServer
> > ```
> 
> thank you so much！ In the path "**/usr/share/honeyd**", s7commServer not found, Do I need to create a s7commServer file? after installing **Honeyd**, will there be this folder?

I would guess so; in my dockerfile i copied the honeyd source code onto the image, and all the setup script did before copying server/s7commserver and that had anything to do with honeyd was call `chmod +x` on `autogen.sh` and `configure` inside the honeyd folder and then call `autogen.sh`, `configure`, `make` and `sudo make install` as per honeyd instructions. So I'm guessing that after installing honeyd the directory exists.

Also take note, it is probably telling you that the folder `/usr/share/honeyd` does not exist, and the last part, `s7commserver` is the new name of the file you are copying, whose original name is `server`. It tries to copy `server` into `/usr/share/honeyd/s7commServer` (and renaming it to s7commserver, try playing around with the cp command in a safe environment to see how it works) but there is no `/usr/share/honeyd/` so that's whats missing; install honeyd first.

I created a gist with my original docker setup script that never saw daylight outside my private repo, but here I hope it helps you: https://gist.github.com/offblacc/0e0e681f960513ea2e3fcb76f02f2f17

This script creates a docker image, but before running the script there are things I copy onto it, check that out here
https://gist.github.com/offblacc/36a1a0b88a9c4f07629dc92792324c86

By the way if you're looking at Docker(files) for the first time, ChatGPT helped me a lot in understanding them and sped up the learning process. I found it quite helpful.

**Comment by ringringboy** [comment]
> > > > > To install the libs:
> > > > > ```shell
> > > > > honeyplc/snap7/build/unix# make -f x86_64_linux.mk install # or whatever your OS is
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Took me some time to find my way through the files and acknowledge the readmes in different subdirs, that helped
> > > > 
> > > > 
> > > > hi，how to install s7commserver,do as this?
> > > > cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer chmod 777 /usr/share/honeyd/s7commServer
> > > 
> > > 
> > > This is from my install script, the part that does s7commserver installation. Just bear in mind - I never got everything to successfully work, I was getting #2 . However, I could successfully start the server (to the best of my knowledge, I installed it successfully). I don't have the virtual machine that this was on anymore, but do have old notes and all of the code backed up so feel free to ask if you get stuck again.
> > > ```shell
> > > # install S7comm Server and library.
> > > cd honeyplc-source/snap7/build/unix
> > > make -f x86_64_linux.mk install
> > > cd ../../../..
> > > 
> > > echo "# ====== S300 fingerprint =======" >> /usr/share/honeyd/nmap-os-db
> > > cat honeyplc-source/plc-profiles/Siemens\ S7-300/s7-300-nmap-fingerprint.txt >> /usr/share/honeyd/nmap-os-db
> > > 
> > > cp honeyplc-source/snap7/build/bin/x86_64-linux/libsnap7.so-300 /usr/lib/
> > > cp honeyplc-source/snap7/examples/cpp/x86_64-linux/server /usr/share/honeyd/s7commServer
> > > chmod 777 /usr/share/honeyd/s7commServer
> > > ```
> > 
> > 
> > thank you so much！ In the path "**/usr/share/honeyd**", s7commServer not found, Do I need to create a s7commServer file? after installing **Honeyd**, will there be this folder?
> 
> I would guess so; in my dockerfile i copied the honeyd source code onto the image, and all the setup script did before copying server/s7commserver and that had anything to do with honeyd was call `chmod +x` on `autogen.sh` and `configure` inside the honeyd folder and then call `autogen.sh`, `configure`, `make` and `sudo make install` as per honeyd instructions. So I'm guessing that after installing honeyd the directory exists.
> 
> Also take note, it is probably telling you that the folder `/usr/share/honeyd` does not exist, and the last part, `s7commserver` is the new name of the file you are copying, whose original name is `server`. It tries to copy `server` into `/usr/share/honeyd/s7commServer` (and renaming it to s7commserver, try playing around with the cp command in a safe environment to see how it works) but there is no `/usr/share/honeyd/` so that's whats missing; install it first.
> 
> I created a gist with my original docker setup script that never saw daylight outside my private repo, but here I hope it helps you: https://gist.github.com/offblacc/0e0e681f960513ea2e3fcb76f02f2f17
> 
> This script creates a docker image, but before running the script there are things I copy onto it, check that out here https://gist.github.com/offblacc/36a1a0b88a9c4f07629dc92792324c86
> 
> By the way if you're looking at Docker(files) for the first time, ChatGPT helped me a lot in understanding them and sped up the learning process. I found it quite helpful.

Express my thanks again, it is very helpful to me, and I will gradually understand and master it

**Comment by ringringboy** [comment]
hi, I use Nmap scan honeyplc through s-info.nse script, my CMD and  scan result is following:

```
sudo honeyd -d -f config.s7-300
nmap -p 102 --script s7-info.nse <ip>

PORT    STATE SERVICE
102/tcp open  iso-tsap
MAC Address: 14:FE:B5:D9:2D:54 (Dell)
```
then i use  **./s7commServer <ip>**  , it work!! but show s7-1200 fingerprint information.

i want to know how to config my **config.s7-300**, then nmap can scan s7-300 fingerprint. second, when i use s7commserver to run, how to change it plc information(fingerprint and network).

I recently deployed conpot and tried to detect Nmap fingerprints. After success, I would like to compare the fingerprint feedback of honeyplc. Thank you very much.

this is my config.s7-300
```
create s7-300
set s7-300 personality "Siemens Simatic 300 programmable logic controller"
set s7-300 default tcp action reset
add s7-300 tcp port 102 "scripts/embedded/snmp/fake-snmp.pl"
set s7-300 ethernet "dell" 
bind <ip> s7-300
```
